### ISSUE TITLE
Error while fetching data on playground.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#113]
### Description

While creating a task using mutation:
```graphql
mutation {
    createTask(input: {
    version: 1,
    title: "Task 1",
    description: "Hello 1",
    status: "Open"   
  }){
 version
  id
  } 
}  
```

I got the following error: 
```graphql
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Task.id.",
 ...
 ```

Why is it returning this instead of returning the id?

**Comment by Lavanyagaur22** [comment]
Also, what's the command to empty the database?

**Comment by Lavanyagaur22** [comment]
Also, upon running queries and mutations on the playground, we are getting this: 

<img width="725" alt="Screenshot 2019-08-12 at 12 25 58 PM" src="https://user-images.githubusercontent.com/33238323/62849235-790a2800-bcfc-11e9-8466-6dbdf9011247.png">

If we don't get any data back, we would be having problems with inflating data in the app.

**Comment by wtrocki** [comment]
@Lavanyagaur22 This is graphback issue. Do you mind dropping this issue text into graphback. I will fix that in our server manually.

**Comment by harshithdwivedi** [comment]
Same here, 

````
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Task.id.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "createTask",
        "id"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Task.id.",
            "    at completeValue (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:596:13)",
            "    at completeValueCatchingError (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:531:19)",
            "    at resolveField (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:471:10)",
            "    at executeFields (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:311:18)",
            "    at collectAndExecuteSubfields (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:747:10)",
            "    at completeObjectValue (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:737:10)",
            "    at completeValue (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:626:12)",
            "    at completeValue (C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:593:21)",
            "    at C:\\Users\\harsh\\Desktop\\graphql\\offix-android\\sample\\server\\node_modules\\graphql\\execution\\execute.js:528:16"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by Lavanyagaur22** [comment]
> Also, upon running queries and mutations on the playground, we are getting this:
> 
> <img alt="Screenshot 2019-08-12 at 12 25 58 PM" width="725" src="https://user-images.githubusercontent.com/33238323/62849235-790a2800-bcfc-11e9-8466-6dbdf9011247.png">
> 
> If we don't get any data back, we would be having problems with inflating data in the app.

@wtrocki @harshithdwivedi If we don't get data back, how we are going to inflate it in app?

**Comment by wtrocki** [comment]
@Lavanyagaur22 This is because you have made some changes that broke it?
I get data back for all queries/mutations. 

Feel free to improve server as you wish.

**Comment by Lavanyagaur22** [comment]
Yeah, was about to close the issue. Getting it now.
